# Credenciais (Vindas do Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Força o Dialect para o Hibernate não tentar adivinhar
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração de sobrevivência para instâncias Free
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5